In [1]:
import sys
import numpy as np


In [2]:
print ("Hello world")

Hello world


# Numpy Arrays

In [3]:
# declaring an array
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [7]:
# declaring an array and initializing it to a variable
a= np.array([1, 2, 3, 4, 5])

In [10]:
# how to find the value of a paricular item using its index which starts from 0
a[4], a[3], a[0]

(5, 4, 1)

In [11]:
# How to find the type of an array 
a.dtype

dtype('int32')

In [13]:
# Declaring an array and changing its type
b = np.array([3, 5, 7, 9, 11], dtype=float)

In [14]:
b.dtype

dtype('float64')

# Dimensions and shapes

In [17]:
# Creating a multidimensional array or matrice
c = np.array([
            [1, 2, 3, 4], 
            [9, 8, 7, 6,]
                        ])

In [18]:
# getting the number of rows and columns of the array
c.shape

(2, 4)

In [19]:
# Getting the dimnsions of the array
c.ndim

2

In [20]:
# getting the total size of the array or total number of elements in the array
c.size

8

In [21]:
# creating a 3 dimensional array, or an array with 2 matrices. 
d = np.array([
            [
            [1, 2, 3, 4, 5],
            [9, 8, 7, 6, 5],
            ],

            [
            [6, 7 ,8, 9, 5],
            [5, 4, 3, 2, 1]
            ]
            
])

In [22]:
# we can then get the details of this array
d.size

20

In [23]:
d.ndim

3

In [24]:
d.shape

(2, 2, 5)

# Indexing and slicing of arrays

In [25]:
e = np.array([
        #index  0   1  2  3
                [1, 2, 3, 4], # index 0
                [3, 4, 5, 6], # index 1
                [6, 7, 8, 9]  # index 2
])

In [26]:
e.shape

(3, 4)

In [27]:
# to get the entire row of an array
e[0]

array([1, 2, 3, 4])

In [29]:
# to get a pecific element you first specify the index of the row in which it is and then the column
e[0][1]

2

In [30]:
# a more efficient way to do it is with one bracket
e[0, 1] 

2

# Slicing Matrices

In [32]:
# we can also select a groupof things in a matrice. like the first two entire rows. 
e[0:2] # This will select the index 0 row and index 1 row but not the row at index 2, this is because the second value i sthe uppper limit


array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [34]:
# This is to select everything in the matrix
e[:]

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [6, 7, 8, 9]])

In [33]:
# we can also select from different dimensions, for example to select all the rows but only two columns
e[:,0:2]


array([[1, 2],
       [3, 4],
       [6, 7]])

# Manipuating Arrays

In [38]:
# you can chnage values in a certain row or column as long as the dimensions match eg
e[1] = np.array([55,23,19,10])

In [39]:
e[:]

array([[ 1,  2,  3,  4],
       [55, 23, 19, 10],
       [ 6,  7,  8,  9]])

In [41]:
# if you are adding the same value, you can add as follows
e[2] = 15
# Lets check the array now
e[:]

array([[ 1,  2,  3,  4],
       [55, 23, 19, 10],
       [15, 15, 15, 15]])

# Summary Statistics 

In [45]:
a[:]

array([1, 2, 3, 4, 5])

In [44]:
# Numpy can compute various statistical information about our data in the arrays
a.sum()

15

In [46]:
# The mean
a.mean()

3.0

In [47]:
# Standard deviation 
a.std()

1.4142135623730951

In [48]:
# The varience
a.var()

2.0

In [49]:
# It can also do the same for matrices
e[:]

array([[ 1,  2,  3,  4],
       [55, 23, 19, 10],
       [15, 15, 15, 15]])

In [52]:
e.sum()

177

In [53]:
e.mean()

14.75

In [54]:
e.std()

13.947072572168446

In [55]:
e.var()

194.52083333333334

In [60]:
# We can also get the statistical summaries of the rows and columns by axis, axis 0 is for the columns and axis 1 is for the rows
e.shape

(3, 4)

In [61]:
#Sum of Columns / axis 0
e.sum(axis=0)


array([71, 40, 37, 29])

In [57]:
# Sum of Rows / axis 1
e.sum(axis=1)

array([ 10, 107,  60])

In [58]:
# Columns means
e.mean(axis=0)

array([23.66666667, 13.33333333, 12.33333333,  9.66666667])

In [62]:
# Row means
e.mean(axis=1)

array([ 2.5 , 26.75, 15.  ])

In [63]:
# Coluumn std deviations
e.std(axis=0)

array([22.8813364 ,  8.65383666,  6.79869268,  4.49691252])

In [64]:
# Row Std deviations
e.std(axis=1)

array([ 1.11803399, 16.97608612,  0.        ])